import torch
import torch.nn as nn
import numpy as np

class EventDetector(nn.Module):
    def __init__(self, input_size=90, hidden_size=128, num_layers=2, num_classes=5):
        """
        Bidirectional LSTM for event detection.
        Classes: none (0), bounce (1), glass_hit (2), net_contact (3), player_hit (4)
        """
        super(EventDetector, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)
        # Bidirectional means output is 2*hidden_size
        self.fc = nn.Linear(hidden_size * 2, num_classes)

    def forward(self, x):
        # x shape: (batch_size, seq_len, input_size)
        # We only care about the output of the last sequence step for classification
        out, _ = self.lstm(x)
        # out shape: (batch_size, seq_len, hidden_size * 2)
        out = self.fc(out[:, -1, :])
        return out

def classify_events(lstm_features_df, model_path=None, window_size=15):
    """
    Classify events using the trained Bi-LSTM model.
    lstm_features_df must have the 90 columns generated by extract_lstm_features.
    """
    print("Classifying events using Bi-LSTM...")

    # Check if we have the features
    feature_cols = [c for c in lstm_features_df.columns if c not in ['frame', 'label']]
    if len(feature_cols) == 0:
        return ["none"] * len(lstm_features_df)

    # We expect 6 base features * 15 window size = 90 features
    input_size = len(feature_cols)
    model = EventDetector(input_size=input_size)

    # In a real scenario, we load weights:
    if model_path:
        try:
            model.load_state_dict(torch.load(model_path))
            model.eval()
        except Exception as e:
            print(f"Could not load Bi-LSTM model from {model_path}: {e}")
            print("Using untrained model (random predictions).")

    events = []
    classes = ["none", "bounce", "glass_hit", "net_contact", "player_hit"]

    # For simplicity, convert the entire dataframe to a tensor
    # The shape should be (num_frames, 1 sequence, input_size)
    # The features are already windowed by extract_lstm_features!
    X = lstm_features_df[feature_cols].values

    with torch.no_grad():
        for i in range(len(X)):
            x_tensor = torch.tensor(X[i], dtype=torch.float32).unsqueeze(0).unsqueeze(0) # (1, 1, input_size)
            outputs = model(x_tensor)
            _, predicted = torch.max(outputs.data, 1)
            events.append(classes[predicted.item()])

    return events
